### PR TITLE
feat(terraform): store plugins in cache

### LINKED ISSUE #237: Cache Terraform provider plugins
Cache Terraform provider plugins to speed up `terraform init` performance.

Could also be useful in disaster recovery scenarios, where we'll be able to run Terraform using cached providers.

- https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

For the GitHub Action, `key` could be `terraform-${{ hashFiles('.terraform.lock.hcl') }}`.

### PR DESCRIPTION
**Pull request by sondresjolyst**
Enable [Terraform plugin caching](https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache) using the [cache action](https://github.com/actions/cache).

Closes #237

### CODE REVIEW

**Comment by hknutsen** [comment]
A thought to consider: how useful is this cache going to be when we could have a large number of different Terraform configurations in a single repository, with different plugin dependencies?

**Comment by hknutsen** [comment]
The following note in [this section](https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache) in the official docs has me thinking that this may not be a good idea:

image

**Comment by hknutsen** [comment]
Considering this as stale for now.

**Comment by hknutsen** [comment]
Plugins are stored as follows: `$TF_PLUGIN_CACHE_DIR/<REGISTRY_URL>/<NAMESPACE>/<PROVIDER>/<VERSION>/<PLATFORM>`.

Since they're stored by version (and even platform), I think we can use a single cache per repo 🤔

**Comment by hknutsen** [comment]
Manually tested in another repo and it works as expected 🎉

**Comment by hknutsen** [comment]
@equinor/ops-actions-maintainers I've tested that this works as expected. Please leave a review when you have time 🙌

**Review by helenakallekleiv — APPROVED** [review]
No comments, looks good👍🏼 ✅

**Pull request merged**
