### PR TITLE
chore: rewrite Terraform backend shell script to external Bicep template

### PR DESCRIPTION
**Pull request by hknutsen**
Rewrite Terraform backend shell script to a Bicep template, and store that template in a separate repository with its own versioning.

Pros:

- A Bicep template should be easier to maintain than a shell script, due to its declarative nature.
- A Bicep template can be deployed without cloning the repo locally.
- Should be able to pass "complex" configuration, such as IP rules and principals IDs, using [parameter files](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep) that can be checked into Git.

Cons:

- Bicep template does not support taking in a raw Terraform backend configuration file as an input.

### CODE REVIEW

**Comment by kov117** [comment]
Yeah based on what i saw, this looks nice 👍🏼 actually like and a bit more understandable for my part on the read me now file. Plus if this gets easier to maintain then i am all for it.

**Comment by sefornes** [comment]
As a long-time Windows user from when Microsoft an the *NIX crowd were mortal enemies, I think Bash scripts on Windows is an abomination (much like Powershell on Linux), so I think this is nice.

**Comment by hknutsen** [comment]
Added a con in the PR description.

**Review by sefornes — APPROVED** [review]

**Comment by hknutsen** [comment]
Experimenting with maintaining this template in a standalone repository: https://github.com/equinor/terraform-backend

Waiting with merge until ewe've decided on something there.

**Comment by hknutsen** [comment]
Should be ready for re-review 😊

**Review by sefornes — APPROVED** [review]

**Pull request merged**
